import {
  Cpu,
  Hammer,
  Database,
  Zap,
  Code,
  Settings,
  LayoutTemplate,
  Box,
  Bot,
  MessageSquare,
  Globe,
  Container,
  Cloud,
  FileJson,
} from "lucide-react";

// --- MAGIC TOOLS DATA ---
export const MAGIC_TOOLS_DATA = [
  {
    category: "Server Boilerplates",
    items: [
      {
        id: "fast-mcp",
        label: "FastMCP Standard",
        desc: "High-level abstraction for quick servers",
        icon: <Zap size={14} className="text-[#ffd740]" />,
        tag: "Boilerplate",
        actionType: "create",
        content: `from mcp.server.fastmcp import FastMCP\n\nmcp = FastMCP("My Agent")\n\n@mcp.tool()\nasync def add(a: int, b: int) -> int:\n    """Add two numbers"""\n    return a + b\n\nif __name__ == "__main__":\n    mcp.run()`,
      },
      {
        id: "fastapi-sse",
        label: "FastAPI SSE Server",
        desc: "Production HTTP/SSE transport",
        icon: <Cloud size={14} className="text-[#00e676]" />,
        tag: "Boilerplate",
        actionType: "create",
        content: `from fastapi import FastAPI\nfrom mcp.server.fastmcp import FastMCP\nimport uvicorn\n\n# Create FastMCP Server\nmcp = FastMCP("Secure Agent")\n\n@mcp.tool()\nasync def echo(text: str) -> str:\n    return f"Echo: {text}"\n\n# Create FastAPI App\napp = FastAPI()\n\n# Mount MCP as SSE\nmcp.mount_sse(app, "/sse")\n\nif __name__ == "__main__":\n    uvicorn.run(app, port=8000)`,
      },
      {
        id: "low-level",
        label: "Low-Level Control",
        desc: "Manual JSON-RPC handling",
        icon: <Code size={14} className="text-[#a0a0b0]" />,
        tag: "Boilerplate",
        actionType: "create",
        content: `import asyncio\nfrom mcp.server import Server\nfrom mcp.server.stdio import stdio_server\n\napp = Server("low-level-demo")\n\n@app.list_tools()\nasync def list_tools():\n    return []\n\nasync def main():\n    async with stdio_server() as (read, write):\n        await app.run(read, write, app.create_initialization_options())\n\nif __name__ == "__main__":\n    asyncio.run(main())`,
      },
    ],
  },
  {
    category: "Complete Servers",
    items: [
      {
        id: "server-basic-math",
        label: "Math Server",
        desc: "Simple calculator tools",
        icon: <Zap size={14} className="text-[#00d4ff]" />,
        tag: "Basic",
        actionType: "create",
        content: `from mcp.server.fastmcp import FastMCP\n\n# Initialize a basic FastMCP server\nmcp = FastMCP("MathService")\n\n@mcp.tool()\nasync def add(a: float, b: float) -> float:\n    """Add two numbers"""\n    return a + b\n\n@mcp.tool()\nasync def multiply(a: float, b: float) -> float:\n    """Multiply two numbers"""\n    return a * b\n\nif __name__ == "__main__":\n    mcp.run()`,
      },
      {
        id: "server-basic-sys",
        label: "System Monitor",
        desc: "Read CPU/RAM stats",
        icon: <Cpu size={14} className="text-[#00d4ff]" />,
        tag: "Basic",
        actionType: "create",
        content: `from mcp.server.fastmcp import FastMCP\nimport psutil # pip install psutil\n\nmcp = FastMCP("SysMonitor")\n\n@mcp.tool()\nasync def get_cpu_usage() -> str:\n    """Get current CPU percentage"""\n    return f"CPU: {psutil.cpu_percent()}%"\n\n@mcp.tool()\nasync def get_memory_usage() -> str:\n    """Get current RAM usage"""\n    mem = psutil.virtual_memory()\n    return f"RAM: {mem.percent}% ({mem.used / (1024**3):.2f}GB used)"\n\nif __name__ == "__main__":\n    mcp.run()`,
      },
      {
        id: "server-adv-kb",
        label: "SQLite Knowledge Base",
        desc: "Persistent RAG system",
        icon: <Database size={14} className="text-[#ff5252]" />,
        tag: "Advanced",
        actionType: "create",
        content: `from mcp.server.fastmcp import FastMCP, Context\nfrom pydantic import BaseModel, Field\nimport sqlite3\nimport json\nfrom typing import List\n\n# Initialize Server\nmcp = FastMCP("KnowledgeBase")\nDB_PATH = "knowledge.db"\n\n# --- Database Management ---\ndef get_db():\n    conn = sqlite3.connect(DB_PATH)\n    conn.row_factory = sqlite3.Row\n    return conn\n\ndef init_db():\n    with get_db() as conn:\n        conn.execute("""\n            CREATE TABLE IF NOT EXISTS entries (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                topic TEXT NOT NULL,\n                content TEXT NOT NULL,\n                tags TEXT,\n                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n            )\n        """)\ninit_db()\n\n# --- Data Models ---\nclass NoteEntry(BaseModel):\n    topic: str = Field(..., description="The main topic of the note")\n    content: str = Field(..., description="The body content")\n    tags: List[str] = Field(default=[], description="List of tags for categorization")\n\n# --- Tools ---\n@mcp.tool()\nasync def add_note(ctx: Context, entry: NoteEntry) -> str:\n    """Add a new note to the knowledge base."""\n    ctx.info(f"Adding note for topic: {entry.topic}")\n    \n    try:\n        with get_db() as conn:\n            tags_json = json.dumps(entry.tags)\n            cursor = conn.execute(\n                "INSERT INTO entries (topic, content, tags) VALUES (?, ?, ?)",\n                (entry.topic, entry.content, tags_json)\n            )\n            note_id = cursor.lastrowid\n            \n        return f"Successfully added note #{note_id} to topic '{entry.topic}'."\n    except Exception as e:\n        ctx.error(f"Failed to write DB: {e}")\n        return f"Error adding note: {str(e)}"\n\n@mcp.tool()\nasync def search_notes(query: str) -> str:\n    """Search notes by topic or content."""\n    with get_db() as conn:\n        cursor = conn.execute(\n            "SELECT id, topic, content FROM entries WHERE topic LIKE ? OR content LIKE ?",\n            (f"%{query}%", f"%{query}%")\n        )\n        rows = cursor.fetchall()\n        \n    if not rows:\n        return "No matching notes found."\n        \n    results = []\n    for row in rows:\n        results.append(f"[#{row['id']}] {row['topic']}: {row['content'][:50]}...")\n    \n    return "\\n".join(results)\n\n# --- Resources ---\n@mcp.resource("kb://all_topics")\ndef list_topics() -> str:\n    """Get a list of all unique topics in the DB."""\n    with get_db() as conn:\n        rows = conn.execute("SELECT DISTINCT topic FROM entries").fetchall()\n    return "\\n".join([r['topic'] for r in rows])\n\nif __name__ == "__main__":\n    mcp.run()`,
      },
      {
        id: "server-adv-weather",
        label: "Weather Agent",
        desc: "API + Caching + Progress",
        icon: <Cloud size={14} className="text-[#00e676]" />,
        tag: "Advanced",
        actionType: "create",
        content: `from mcp.server.fastmcp import FastMCP, Context\nimport httpx\nimport asyncio\nfrom datetime import datetime, timedelta\n\nmcp = FastMCP("WeatherAgent")\n\n# --- In-Memory Caching ---\n_CACHE = {}\n_CACHE_TTL = 300  # 5 minutes\n\nclass WeatherCache:\n    @staticmethod\n    def get(key):\n        if key in _CACHE:\n            data, timestamp = _CACHE[key]\n            if datetime.now() - timestamp < timedelta(seconds=_CACHE_TTL):\n                return data\n            del _CACHE[key]\n        return None\n\n    @staticmethod\n    def set(key, data):\n        _CACHE[key] = (data, datetime.now())\n\n# --- Tools ---\n@mcp.tool()\nasync def get_forecast(ctx: Context, city: str, days: int = 1) -> str:\n    """\n    Get weather forecast for a specific city.\n    Uses OpenMeteo API (no key required).\n    """\n    city = city.lower().strip()\n    cache_key = f"{city}_{days}"\n    \n    # 1. Check Cache\n    cached = WeatherCache.get(cache_key)\n    if cached:\n        ctx.info(f"Returning cached data for {city}")\n        return cached\n\n    ctx.info(f"Fetching fresh data for {city}...")\n    await ctx.report_progress(10, 100)\n\n    async with httpx.AsyncClient() as client:\n        # 2. Geocoding\n        try:\n            geo_url = f"https://geocoding-api.open-meteo.com/v1/search?name={city}&count=1&language=en&format=json"\n            geo_resp = await client.get(geo_url)\n            geo_data = geo_resp.json()\n            \n            if not geo_data.get("results"):\n                return f"Error: City '{city}' not found."\n                \n            lat = geo_data["results"][0]["latitude"]\n            lon = geo_data["results"][0]["longitude"]\n            await ctx.report_progress(50, 100)\n            \n            # 3. Weather Fetch\n            weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=auto&forecast_days={days}"\n            weather_resp = await client.get(weather_url)\n            weather_data = weather_resp.json()\n            \n        except Exception as e:\n            return f"API Error: {str(e)}"\n\n    # 4. Format Output\n    daily = weather_data.get("daily", {})\n    output = [f"Weather Forecast for {city.title()} ({days} days):"]\n    \n    for i in range(len(daily.get("time", []))):\n        date = daily["time"][i]\n        temp_max = daily["temperature_2m_max"][i]\n        temp_min = daily["temperature_2m_min"][i]\n        precip = daily["precipitation_sum"][i]\n        output.append(f"- {date}: High {temp_max}°C, Low {temp_min}°C, Rain {precip}mm")\n\n    result = "\\n".join(output)\n    \n    # 5. Cache result\n    WeatherCache.set(cache_key, result)\n    await ctx.report_progress(100, 100)\n    \n    return result\n\n# --- Prompts ---\n@mcp.prompt()\ndef weather_report_template(city: str) -> str:\n    """Template for generating a weather report"""\n    return f"""\n    You are a weather reporter.\n    Please use the \`get_forecast\` tool to find the weather for {city}.\n    Then, write a short, friendly summary of the weather outlook.\n    """\n\nif __name__ == "__main__":\n    mcp.run()`,
      },
    ],
  },
  {
    category: "Advanced Patterns",
    items: [
      {
        id: "rag-vector",
        label: "RAG / Vector DB",
        desc: "Context retrieval pattern",
        icon: <Database size={14} className="text-[#ff5252]" />,
        tag: "Pattern",
        actionType: "insert",
        content: `\n@mcp.resource("rag://{query}")\nasync def search_knowledge_base(query: str) -> str:\n    """Semantic search over documentation"""\n    # Mock Vector DB call\n    # results = vector_db.query(query)\n    return f"Found relevant docs for: {query}"\n`,
      },
      {
        id: "web-scraper",
        label: "Web Scraper",
        desc: "Fetch web content tool",
        icon: <Globe size={14} className="text-[#00d4ff]" />,
        tag: "Pattern",
        actionType: "insert",
        content: `\n@mcp.tool()\nasync def fetch_url(url: str) -> str:\n    """Fetch content from a URL"""\n    import httpx\n    async with httpx.AsyncClient() as client:\n        resp = await client.get(url)\n        return resp.text[:2000] # Return first 2k chars\n`,
      },
    ],
  },
  {
    category: "MCP Tools (Basic)",
    items: [
      {
        id: "tool-calc",
        label: "Calculator",
        desc: "Simple math operation",
        icon: <Hammer size={14} className="text-[#00d4ff]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.tool()\nasync def calculate_sum(a: int, b: int) -> int:\n    """Add two integers together"""\n    return a + b\n`,
      },
      {
        id: "tool-greet",
        label: "Greeter",
        desc: "String manipulation",
        icon: <Hammer size={14} className="text-[#00d4ff]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.tool()\nasync def greet_user(name: str) -> str:\n    """Return a greeting message"""\n    return f"Hello, {name}! Welcome to MCP."\n`,
      },
      {
        id: "tool-rand",
        label: "Randomizer",
        desc: "Generate random data",
        icon: <Hammer size={14} className="text-[#00d4ff]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\nimport random\n\n@mcp.tool()\nasync def roll_dice(sides: int = 6) -> int:\n    """Roll a virtual dice"""\n    return random.randint(1, sides)\n`,
      },
      {
        id: "tool-status",
        label: "System Check",
        desc: "Simple status check",
        icon: <Hammer size={14} className="text-[#00d4ff]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.tool()\nasync def check_status() -> str:\n    """Check if the system is online"""\n    return "System is operational"\n`,
      },
    ],
  },
  {
    category: "MCP Tools (Advanced)",
    items: [
      {
        id: "tool-pydantic",
        label: "Structured Validation",
        desc: "Complex args with Pydantic",
        icon: <Hammer size={14} className="text-[#00d4ff]" />,
        tag: "Advanced",
        actionType: "insert",
        content: `\nfrom pydantic import BaseModel, Field, EmailStr\nimport json\n\nclass UserRegistration(BaseModel):\n    username: str = Field(..., min_length=3, max_length=20)\n    email: EmailStr\n    age: int = Field(..., ge=18, lt=100)\n    preferences: dict = Field(default_factory=dict)\n\n@mcp.tool()\nasync def register_new_user(data: UserRegistration) -> str:\n    """\n    Register a new user with strict validation rules.\n    Ensures unique username and compliant age requirements.\n    """\n    # 1. Simulate DB simulation\n    if data.username.lower() == "admin":\n        return "Error: 'admin' is a reserved username."\n\n    # 2. Process preferences\n    theme = data.preferences.get("theme", "dark")\n    \n    # 3. Return structured JSON response\n    return json.dumps({\n        "status": "success",\n        "id": f"u_{data.username}_123",\n        "message": f"User {data.username} registered successfully.",\n        "settings": {"theme": theme}\n    }, indent=2)\n`,
      },
      {
        id: "tool-context",
        label: "Context & Progress",
        desc: "Long tasks with feedback",
        icon: <Hammer size={14} className="text-[#00d4ff]" />,
        tag: "Advanced",
        actionType: "insert",
        content: `\nfrom mcp.server.fastmcp import Context\nimport asyncio\n\n@mcp.tool()\nasync def analyze_large_dataset(ctx: Context, dataset_id: str, operations: list[str]) -> str:\n    """\n    Perform a multi-step analysis on a dataset.\n    Reports real-time progress back to the client.\n    """\n    ctx.info(f"Starting analysis for dataset: {dataset_id}")\n    total_steps = len(operations) + 1\n    results = {}\n\n    # Step 1: Initialization\n    await ctx.report_progress(0, total_steps)\n    await asyncio.sleep(0.5) # Simulate setup\n\n    # Step 2: Run Operations\n    for i, op in enumerate(operations, 1):\n        ctx.info(f"Running operation: {op}")\n        # Simulate complex work\n        await asyncio.sleep(1)\n        results[op] = "Completed"\n        await ctx.report_progress(i, total_steps)\n\n    # Finalize\n    await ctx.report_progress(total_steps, total_steps)\n    return f"Analysis Complete. Results: {results}"\n`,
      },
    ],
  },
  {
    category: "MCP Resources (Basic)",
    items: [
      {
        id: "res-config",
        label: "App Config",
        desc: "Static JSON resource",
        icon: <Database size={14} className="text-[#ff5252]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.resource("config://app")\nasync def get_config() -> str:\n    """Return application configuration"""\n    return '{"version": "1.0", "env": "dev"}'\n`,
      },
      {
        id: "res-note",
        label: "Daily Note",
        desc: "Simple text resource",
        icon: <Database size={14} className="text-[#ff5252]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.resource("note://daily")\nasync def get_daily_note() -> str:\n    """Read the daily MOTD"""\n    return "Remember to hydrate and commit your code!"\n`,
      },
      {
        id: "res-logs",
        label: "System Logs",
        desc: "Read-only string data",
        icon: <Database size={14} className="text-[#ff5252]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.resource("logs://recent")\nasync def get_recent_logs() -> str:\n    """Fetch last 3 log entries"""\n    return "Log 1: OK\\nLog 2: Warn\\nLog 3: OK"\n`,
      },
      {
        id: "res-users",
        label: "User List",
        desc: "Static data list",
        icon: <Database size={14} className="text-[#ff5252]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.resource("data://users")\nasync def list_users() -> str:\n    """Get list of active users"""\n    return "Alice, Bob, Charlie"\n`,
      },
    ],
  },
  {
    category: "MCP Resources (Advanced)",
    items: [
      {
        id: "res-dynamic",
        label: "Dynamic Analytics",
        desc: "URI templates & Validation",
        icon: <Database size={14} className="text-[#ff5252]" />,
        tag: "Advanced",
        actionType: "insert",
        content: `\nfrom datetime import datetime\n\n@mcp.resource("sales://{region}/{year}/report")\nasync def get_sales_report(region: str, year: str) -> str:\n    """\n    Dynamically generate a report for a region/year.\n    URI: sales://us-east/2024/report\n    """\n    # 1. Validate Input\n    valid_regions = ["us-east", "us-west", "eu-central"]\n    if region not in valid_regions:\n        return f"Error: Invalid region '{region}'"\n    \n    if not year.isdigit():\n        return "Error: Year must be numeric"\n\n    # 2. Simulate Data Retrieval\n    generated_at = datetime.now().isoformat()\n    \n    # 3. Construct Document\n    return f"""\n# Sales Report ({year})\nRegion: {region.upper()}\nGenerated: {generated_at}\n\n## Metrics\n- Revenue: $1.2M\n- Growth: +15%\n"""\n`,
      },
      {
        id: "res-binary",
        label: "Binary Stream",
        desc: "Serve generated images",
        icon: <Database size={14} className="text-[#ff5252]" />,
        tag: "Advanced",
        actionType: "insert",
        content: `\nimport io\n# Requires: pip install pillow\n# from PIL import Image, ImageDraw\n\n@mcp.resource("chart://{type}/{data}")\nasync def get_chart_image(type: str, data: str) -> bytes:\n    """\n    Generates a dynamic PNG chart resource.\n    URI: chart://bar/10,20,30\n    """\n    # 1. Parse Data\n    values = [int(x) for x in data.split(",") if x.isdigit()]\n    \n    # 2. Mock Binary Generation (Simulating Bytes)\n    # In prod, use: img.save(byte_io, format='PNG')\n    \n    output = io.BytesIO()\n    header = f"FAKE_PNG_HEADER_{type.upper()}".encode('utf-8')\n    payload = str(values).encode('utf-8')\n    \n    output.write(header + payload)\n    output.seek(0)\n    return output.read()\n`,
      },
    ],
  },
  {
    category: "MCP Prompts (Basic)",
    items: [
      {
        id: "prompt-review",
        label: "Code Review",
        desc: "Standard review template",
        icon: <LayoutTemplate size={14} className="text-[#7c4dff]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.prompt()\ndef code_review(code: str) -> str:\n    """Template for code review requests"""\n    return f"Please review the following code for security and performance issues:\\n\\n{code}"\n`,
      },
      {
        id: "prompt-bug",
        label: "Bug Report",
        desc: "Issue reporting structure",
        icon: <LayoutTemplate size={14} className="text-[#7c4dff]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.prompt()\ndef bug_report(error: str, context: str) -> str:\n    """Standard bug report format"""\n    return f"Error: {error}\\nContext: {context}\\nPlease analyze the root cause."\n`,
      },
      {
        id: "prompt-sum",
        label: "Summarizer",
        desc: "Text summarization",
        icon: <LayoutTemplate size={14} className="text-[#7c4dff]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.prompt()\ndef summarize_text(text: str) -> str:\n    """Summarize long text"""\n    return f"Please provide a concise 3-bullet summary of:\\n\\n{text}"\n`,
      },
      {
        id: "prompt-test",
        label: "Test Gen",
        desc: "Unit test creator",
        icon: <LayoutTemplate size={14} className="text-[#7c4dff]" />,
        tag: "Basic",
        actionType: "insert",
        content: `\n@mcp.prompt()\ndef generate_tests(func_signature: str) -> str:\n    """Create unit tests"""\n    return f"Write pytest unit tests for this function signature:\\n{func_signature}"\n`,
      },
    ],
  },
  {
    category: "MCP Prompts (Advanced)",
    items: [
      {
        id: "prompt-incident",
        label: "Incident Cmdr",
        desc: "Complex role-play",
        icon: <LayoutTemplate size={14} className="text-[#7c4dff]" />,
        tag: "Advanced",
        actionType: "insert",
        content: `\n@mcp.prompt()\ndef incident_response(severity: str, logs: str) -> str:\n    """\n    Generates a full Incident Commander context based on severity.\n    Adjusts protocol automatically.\n    """\n    protocol = "STANDARD"\n    if severity.lower() in ["critical", "sev0", "high"]:\n        protocol = "EMERGENCY_WAR_ROOM"\n\n    return f"""\n    # INCIDENT RESPONSE\n    **Role:** Incident Commander\n    **Protocol:** {protocol}\n    \n    ## Logs Analysis\n    {logs}\n    \n    ## Instructions\n    1. Identify root cause.\n    2. Propose mitigation.\n    3. Draft status update.\n    """\n`,
      },
      {
        id: "prompt-rag",
        label: "RAG Assistant",
        desc: "Context-aware response",
        icon: <LayoutTemplate size={14} className="text-[#7c4dff]" />,
        tag: "Advanced",
        actionType: "insert",
        content: `\n@mcp.prompt()\ndef customer_support_rag(query: str, user_tier: str, docs: list[str]) -> str:\n    """\n    Constructs a RAG prompt with tone adjustment based on user tier.\n    """\n    formatted_docs = "\\n\\n".join([f"Doc {i}: {d}" for i, d in enumerate(docs, 1)])\n    \n    tone = "helpful" if user_tier == "free" else "concierge white-glove"\n    \n    return f"""\n    You are a Support Agent (Tone: {tone}).\n    User Query: {query}\n    \n    Using ONLY the following docs:\n    {formatted_docs}\n    \n    Answer the query. If unknown, admit it.\n    """\n`,
      },
    ],
  },
  {
    category: "Essential APIs",
    items: [
      {
        id: "api-openai",
        label: "OpenAI Chat",
        desc: "Call GPT-4o from a tool",
        icon: <Bot size={14} className="text-[#00e676]" />,
        tag: "Integration",
        actionType: "insert",
        content: `\nimport openai\nimport os\n\n@mcp.tool()\nasync def ask_gpt(prompt: str) -> str:\n    """Ask GPT-4o a question"""\n    client = openai.AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))\n    response = await client.chat.completions.create(\n        model="gpt-4o",\n        messages=[{"role": "user", "content": prompt}]\n    )\n    return response.choices[0].message.content\n`,
      },
      {
        id: "api-ddg",
        label: "DuckDuckGo Search",
        desc: "Free web search",
        icon: <Globe size={14} className="text-[#ffd740]" />,
        tag: "Integration",
        actionType: "insert",
        content: `\nfrom duckduckgo_search import DDGS\n\n@mcp.tool()\nasync def web_search(query: str) -> str:\n    """Search the web for information"""\n    results = DDGS().text(query, max_results=3)\n    return str(results)\n`,
      },
      {
        id: "api-sqlite",
        label: "SQLite Database",
        desc: "Local persistent storage",
        icon: <Database size={14} className="text-[#00d4ff]" />,
        tag: "Database",
        actionType: "insert",
        content: `\nimport sqlite3\n\n# Initialize DB\nconn = sqlite3.connect("mcp.db", check_same_thread=False)\nconn.execute("CREATE TABLE IF NOT EXISTS notes (id INTEGER PRIMARY KEY, content TEXT)")\n\n@mcp.tool()\nasync def add_note(content: str) -> str:\n    """Save a note to the database"""\n    cursor = conn.cursor()\n    cursor.execute("INSERT INTO notes (content) VALUES (?)", (content,))\n    conn.commit()\n    return "Note saved."\n\n@mcp.resource("db://notes")\nasync def get_notes() -> str:\n    """Read all notes"""\n    cursor = conn.cursor()\n    rows = cursor.execute("SELECT content FROM notes").fetchall()\n    return "\\n".join([r[0] for r in rows])\n`,
      },
      {
        id: "api-slack",
        label: "Slack Notification",
        desc: "Send messages to Slack",
        icon: <MessageSquare size={14} className="text-[#ff5252]" />,
        tag: "Integration",
        actionType: "insert",
        content: `\nimport httpx\nimport os\n\n@mcp.tool()\nasync def send_slack_msg(message: str) -> str:\n    """Send a message to Slack via Webhook"""\n    url = os.getenv("SLACK_WEBHOOK_URL")\n    async with httpx.AsyncClient() as client:\n        resp = await client.post(url, json={"text": message})\n        return "Message sent" if resp.status_code == 200 else f"Failed: {resp.text}"\n`,
      },
      {
        id: "api-github",
        label: "GitHub Issues",
        desc: "Fetch repo issues",
        icon: <Code size={14} className="text-[#a0a0b0]" />,
        tag: "Integration",
        actionType: "insert",
        content: `\nimport httpx\n\n@mcp.tool()\nasync def get_github_issues(owner: str, repo: str) -> str:\n    """Get latest open issues from a GitHub repo"""\n    url = f"https://api.github.com/repos/{owner}/{repo}/issues"\n    async with httpx.AsyncClient() as client:\n        resp = await client.get(url, headers={"User-Agent": "MCP-Agent"})\n        issues = resp.json()\n        return "\\n".join([f"#{i['number']}: {i['title']}" for i in issues[:5]])\n`,
      },
    ],
  },
  {
    category: "Deployment & Config",
    items: [
      {
        id: "dockerfile",
        label: "Dockerfile",
        desc: "Containerize server",
        icon: <Container size={14} className="text-[#00d4ff]" />,
        tag: "Config",
        actionType: "create",
        content: `FROM python:3.10-slim\n\nWORKDIR /app\nCOPY . .\nRUN pip install mcp[fastapi] uvicorn\n\nCMD ["python", "server.py"]`,
      },
      {
        id: "claude-config",
        label: "Claude Config",
        desc: "Connect to Desktop App",
        icon: <FileJson size={14} className="text-[#ffd740]" />,
        tag: "Config",
        actionType: "create",
        content: `{\n  "mcpServers": {\n    "my-local-server": {\n      "command": "python",\n      "args": ["/absolute/path/to/server.py"]\n    }\n  }\n}`,
      },
      {
        id: "smithery",
        label: "Smithery Manifest",
        desc: "Publish to Registry",
        icon: <Box size={14} className="text-[#a0a0b0]" />,
        tag: "Config",
        actionType: "create",
        content: `{\n  "name": "my-mcp-server",\n  "version": "1.0.0",\n  "description": "An amazing MCP server",\n  "entry": "server.py"\n}`,
      },
    ],
  },
  {
    category: "Utilities",
    items: [
      {
        id: "util-env",
        label: "Load .env",
        desc: "Python dotenv setup",
        icon: <Settings size={14} className="text-[#a0a0b0]" />,
        tag: "Utility",
        actionType: "insert",
        content: `from dotenv import load_dotenv\nimport os\n\nload_dotenv()\napi_key = os.getenv("API_KEY")\n`,
      },
      {
        id: "util-http",
        label: "Async HTTP Client",
        desc: "Httpx client setup",
        icon: <Box size={14} className="text-[#a0a0b0]" />,
        tag: "Utility",
        actionType: "insert",
        content: `import httpx\n\nasync with httpx.AsyncClient() as client:\n    response = await client.get("https://api.example.com")\n    data = response.json()\n`,
      },
    ],
  },
];

export const BADGE_MAP = {
  Advanced: { c: "var(--red)", bg: "var(--red-dim)", bdr: "var(--red-bdr)" },
  Basic: {
    c: "var(--c-tool)",
    bg: "rgba(77,143,204,.1)",
    bdr: "rgba(77,143,204,.22)",
  },
  Boilerplate: {
    c: "var(--amber)",
    bg: "var(--amber-dim)",
    bdr: "var(--amber-bdr)",
  },
  Pattern: { c: "var(--a)", bg: "var(--a-dim)", bdr: "var(--a-bdr)" },
  Config: { c: "var(--t2)", bg: "var(--s2)", bdr: "var(--b1)" },
  Utility: {
    c: "var(--green)",
    bg: "var(--green-dim)",
    bdr: "var(--green-bdr)",
  },
};
